### ISSUE TITLE
Add database schema to documentation

### ISSUE THREAD

**Issue by timtomch** [NationalGalleryOfArt/opendata#2]
Hello and thank you for making your data available for reuse!

I am working with the [Curationist project](https://www.curationist.org/about-us/), a platform to collate openly available artworks from multiple museums and cultural institutions, including the National Gallery of Art.

We were able to import your data and map it to our own schema thanks to the documentation you provided, however we had to work our way through your relational database schema in order to figure out how the multiple tables work together (see attached). Future users of your data may appreciate having the schema described this way, so if you want to add it to the documentation, please feel free to reuse and expand on what we have done! The SVG file should be editable.

Thank you.

![natgal-dbschema](https://user-images.githubusercontent.com/7302575/152837215-46454efb-9b7d-4b40-986f-4a27024d5598.svg)

**Comment by mehdi-nga** [comment]
Thomas,
Thank you so much to share this with us.  It will be an useful resource for the users of our data. We will add this documentation to our repo after it is reviewed and verified.

**Comment by brwz-nga** [comment]
Hi Thomas,

We have reviewed and verified the database schema and have added it to the documentation.
