### ISSUE TITLE
Wikidata IDs for NGA objects and constituents.

### ISSUE THREAD

**Issue by bzweig633** [NationalGalleryOfArt/opendata#6]
Include Wikidata IDs for NGA objects in objects.csv file and for NGA constituents in constituents.csv file.

**Comment by beaudet** [comment]
Now that Wikidata IDs have been added to the collection management system, this will just require adding the right alt number type for Wikidata IDs in the collection data extraction process.

**Comment by beaudet** [comment]
Refined requirements after some internal team discussion:
- create a new project branch for this activity
- drop the objects_altnums table
- create a new alternative_identifiers table which consists of entity UUIDs, a label for the identifier, e.g. Wikidata ID, and the identifier value (new table may contain identifiers for any entity, not just objects). 
- add a "WikidataID" column to the objects table
- add a "WikidataID" column to the constituents table
- add the RKDArtists identifiers to the alternative_identifiers table
- edit the documentation accordingly

**Comment by beaudet** [comment]
branch altIdentifiers created for @brwz-nga review and to accept updates to the documentation.  Will merge and enable new scripts after review and documentation  updates are complete.

**Comment by beaudet** [comment]
The data should be in place for wikidata IDs.  Please take a look.

**Comment by beaudet** [comment]
Wikidata IDs have been added to the data set, the data dictionary, and the README file. Work is now complete.  Closing issue.
